# Generated by Django 4.0.1 on 2022-02-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_blogcomment_delete_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='sno',
        ),
    ]
