# Generated by Django 4.0.1 on 2022-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0007_rename_id_post_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
